### PR TITLE
Improve dark mode

### PR DESCRIPTION
**Pull request by Onurtag**
Rewrite dark mode css to make it look more modern.  

Let me know if anything is broken so I can fix it.

### CODE REVIEW

**Comment by jingyu9575** [comment]
Hi @Onurtag , sorry for the delay. The 3.2b6 version is still pending review because of [this issue](https://github.com/jingyu9575/multithreaded-download-manager/issues/180#issuecomment-1261635277). After it passed I'll merge the CSS.

**Comment by Onurtag** [comment]
No problem. The delay gave me enough time to fix it up properly.
Now it should look much closer to default firefox dark theme.

Let me know if you see any problems.

**Comment by Onurtag** [comment]
You can close #181 and #133 after the merge.

**Comment by jingyu9575** [comment]
Finally the extension has passed review. I'll check the dark theme this weekend.

**Comment by jingyu9575** [comment]
Thank you! I've submitted the new version for review.

**Comment by Onurtag** [comment]
Great! Hope the review goes smooth this time.

**Comment by jingyu9575** [comment]
v3.2b8 is approved.

**Comment by Onurtag** [comment]
Great!

**Pull request merged**
