### PR TITLE
Create messages.cson Russian

### PR DESCRIPTION
**Pull request by wvxwxvw**
Wanted to check at myself, but conversion from .cson in .json is a little more than I'm ready for. =) So if there are flaws, then I will fix them later. I'm waiting for the Russian version!

### CODE REVIEW

**Comment by jingyu9575** [comment]
Thank you!

Why have you shorten the extension name to "Multithread DM"? Is `DM` a common abbreviation in Russian?

**Comment by wvxwxvw** [comment]
1. Yes.
2. Even for the English version, an unnecessarily long line looks ugly. After all, the name goes to the context menu item and the sidebar title!!!!

**Comment by wvxwxvw** [comment]
I would do a rebranding. =)

**Comment by jingyu9575** [comment]
> an unnecessarily long line looks ugly

I did not know this problem because I am using the Chinese version. Yes the long line is ugly, but I think it is too late to change now.

**Pull request merged**
